disabled_rules:
    - line_length
    - identifier_name
    - type_name
    - function_parameter_count

included:
  - Sources

warning_threshold: 1

private_over_fileprivate:
  validate_extensions: true

file_length:
  warning: 485
  error: 500

