language: objective-c
osx_image: xcode7.3

before_install:
- set -o pipefail
- xcodebuild -version
- xcodebuild -showsdks
- brew update
- brew outdated carthage || brew upgrade carthage
- carthage update Result --platform all
- carthage update Nimble --platform iOS,Mac,tvOS
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
- defaults write com.apple.dt.Xcode UseSanitizedBuildSystemEnvironment -bool NO
script:
- xcodebuild clean build -project FaunaDB.xcodeproj -scheme  "FaunaDB iOS" -sdk iphonesimulator | xcpretty -c
- xcodebuild clean build -project FaunaDB.xcodeproj -scheme  "FaunaDB OSX" -sdk macosx | xcpretty -c
- xcodebuild clean build -project FaunaDB.xcodeproj -scheme  "FaunaDB tvOS" -sdk appletvsimulator | xcpretty -c
- xcodebuild clean build -project FaunaDB.xcodeproj -scheme  "FaunaDB watchOS" -sdk watchsimulator | xcpretty -c
- xcodebuild test -project FaunaDB.xcodeproj -scheme "FaunaDB iOS" -sdk iphonesimulator FAUNA_ROOT_KEY=$FAUNA_ROOT_KEY | xcpretty -c
- xcodebuild test -project FaunaDB.xcodeproj -scheme "FaunaDB OSX" -sdk macosx FAUNA_ROOT_KEY=$FAUNA_ROOT_KEY | xcpretty -c
- xcodebuild test -project FaunaDB.xcodeproj -scheme "FaunaDB tvOS" -sdk appletvsimulator -destination="platform=tvOS Simulator" FAUNA_ROOT_KEY=$FAUNA_ROOT_KEY | xcpretty -c
env:
  global:
    - secure: "Mc/gjfA9ijal7xTCLt4FpRVlfWmZxdPWJmfHH7DObvLCXw0AGcBE8k15NXUmWAVIirCeuoed1TiAdSsFQu5JPWSRXrpRv6qz5UeiioCVMRzclkgTNFO2QeS4TWenJnqoet/NDSD+5gaBFnDZWd9lVC/SZD+N+ufNX+GWw1RK9SPogpEmyv13gnbVXDtv+qoV8Yb2HjyZ9wxSevPxC+O/oxXbOkgaxBQQcZU2v94DoamGUs+5dsiU07/AFh5aHtKzZD+byIzbEb2S+oaMUHJJ2DAPjlEZEa1OLPSElOy6DPY/NxRTiUmseGIHpg0695RtoG3RcIZ/U1I2YJMGuGypOTW7HcWK5A/3OkamHJiQKEddjrDEUvDLzNmqasc9pVHBy4to4muil2kMF6nXfyDt/k5Fx4Btq550uC0IO0LykdponCqqgSTTPZtJ7oen716B++TN0CAVmm+DCQP0/dpd3SI9vFc+xzO1FRppFd6YnJfYd0+UvC6VBgDM/M/VpGMgcpB+Pl1Jmzu7Xk89ZEsOaeOJJ4KeZkC4PkZnJWOZAIaLYqwTA1AarqLBw0ysI3YKX39EfiJPFFor6I87A/f3P/MprpWaMy5dGWMBmeQJYM/XYWfFd4Nlgv0Re4rZzn5zdD7AieSfgV0XSrLR34vKmG1FB4q+GtnCA85EfOiaJNk="
branches:
  only:
    - master
notifications:
  email: false
