language: objective-c
osx_image: xcode8
env:
  global:
  - FAUNA_ENDPOINT=db.faunadb.com
  - secure: Mc/gjfA9ijal7xTCLt4FpRVlfWmZxdPWJmfHH7DObvLCXw0AGcBE8k15NXUmWAVIirCeuoed1TiAdSsFQu5JPWSRXrpRv6qz5UeiioCVMRzclkgTNFO2QeS4TWenJnqoet/NDSD+5gaBFnDZWd9lVC/SZD+N+ufNX+GWw1RK9SPogpEmyv13gnbVXDtv+qoV8Yb2HjyZ9wxSevPxC+O/oxXbOkgaxBQQcZU2v94DoamGUs+5dsiU07/AFh5aHtKzZD+byIzbEb2S+oaMUHJJ2DAPjlEZEa1OLPSElOy6DPY/NxRTiUmseGIHpg0695RtoG3RcIZ/U1I2YJMGuGypOTW7HcWK5A/3OkamHJiQKEddjrDEUvDLzNmqasc9pVHBy4to4muil2kMF6nXfyDt/k5Fx4Btq550uC0IO0LykdponCqqgSTTPZtJ7oen716B++TN0CAVmm+DCQP0/dpd3SI9vFc+xzO1FRppFd6YnJfYd0+UvC6VBgDM/M/VpGMgcpB+Pl1Jmzu7Xk89ZEsOaeOJJ4KeZkC4PkZnJWOZAIaLYqwTA1AarqLBw0ysI3YKX39EfiJPFFor6I87A/f3P/MprpWaMy5dGWMBmeQJYM/XYWfFd4Nlgv0Re4rZzn5zdD7AieSfgV0XSrLR34vKmG1FB4q+GtnCA85EfOiaJNk=
  matrix:
  - iOS= DESTINATION='platform=iOS Simulator,name=iPhone 6S'
  - tvOS= DESTINATION='platform=tvOS Simulator,name=Apple TV 1080p'
  - macOS= DESTINATION='platform=OS X'
  - watchOS= DESTINATION='platform=watchOS Simulator,name=Apple Watch - 38mm'
script:
- set -o pipefail && xcodebuild test -scheme "FaunaDB" -destination "$DESTINATION"
  FAUNA_ROOT_KEY="$FAUNA_ROOT_KEY" FAUNA_ENDPOINT="$FAUNA_ENDPOINT" | xcpretty
branches:
  only:
  - master
notifications:
  email: false
  slack:
    secure: faDQKBMA/B501n+F1X8VCCBk6qvonOUZsGWOK68OEWpqcpIKc4i0vDFYQCsJi6eKwNTD7SFAGvfi8VwoB/3qkBU9s7N9z2mLHpBmu8jndl6r5xt+r1vdwGl9zYPDYjdCEx6MXkJwg1HZ38Kd/QLUFqf93JNcn9/yBRVqri81XQ5IWqpxRMmhPxTjvuAWWskapBNutD+Cf27ZJrdkYrG+G6yUY29Dkez5b1M4TFe7sarFReqb5WAUVGjU/4dT6PVcVv45nIu+9G5iuqVSIczE9/7eLEbbzLFZzr/Ki/4Qr08i9POCdarYL7moBxpgnYGGIH1RedugRGjSXpd6C4VxgSBlpg/6aavl4C/6PHzmC8Oiuder3hHS/0CP+qdjBJCRHdfKpzChbB4w8kG7jAGobFp2BbcrlxqYObubsknjkb1RXVZ89X0PViAJk71ziitoEO4GZNA4tBXcMx5dQ0/zDpbHZmRgl4iM0hbh3lF1SOfxrM3Q65Jbb/Bn5fnYL1b9LpqoL4CPF/jt09Cd5S7U5WbI2mj9/Usw7Z7AgRvu5tHv7MZdvytDwNjEzbGtcTJAp4qiMkav8O2jK/EjlHcPhGXdYg/qO+9yuo8zO311S/4LjPOkCfncWJFC+1FAZJK0WMJF/xrG+9P8GvFYsRCqlmfVQK0WHSRiZ8LRfocpAk0=
